globalThis.ROOMARK_PROPERTIES = [
  {
    id: "H01",
    title: "晨光 L 型两居",
    latitude: 31.2308,
    longitude: 121.4682,
    address: "静安区新闸路 928 号",
    price: "¥4,800/月",
    deposit: "¥4,800",
    moveInCost: "约 ¥14,400",
    commuteMinutes: 18,
    distance: "1.2 km",
    riskCount: 2,
    highRiskCount: 1,
    score: 86,
    status: "scanned",
    statusLabel: "已扫描 · 已完成软装",
    isFavorite: true,
    hasVisited: true,
    hasEvidence: true,
    hasScan: true,
    hasFurnishLayout: true,
    evidenceCount: 6,
    riskSummary: "卫生间墙角有潮痕，签约前建议确认维修记录。",
    thumbnail: "morning"
  },
  {
    id: "H02",
    title: "北岛中庭公寓",
    latitude: 31.2366,
    longitude: 121.4775,
    address: "静安区康定东路 166 号",
    price: "¥5,600/月",
    deposit: "¥5,600",
    moveInCost: "约 ¥16,800",
    commuteMinutes: 26,
    distance: "2.4 km",
    riskCount: 3,
    highRiskCount: 0,
    score: 82,
    status: "visited",
    statusLabel: "已现场看房",
    isFavorite: true,
    hasVisited: true,
    hasEvidence: true,
    hasScan: false,
    hasFurnishLayout: false,
    evidenceCount: 5,
    riskSummary: "中庭采光较好，厨房通风和水电表读数仍需补拍。",
    thumbnail: "courtyard"
  },
  {
    id: "H03",
    title: "海岸双卧套房",
    latitude: 31.2252,
    longitude: 121.4828,
    address: "黄浦区南苏州路 318 号",
    price: "¥5,200/月",
    deposit: "¥5,200",
    moveInCost: "约 ¥15,600",
    commuteMinutes: 34,
    distance: "3.1 km",
    riskCount: 5,
    highRiskCount: 2,
    score: 74,
    status: "risk",
    statusLabel: "高风险 · 已看房",
    isFavorite: false,
    hasVisited: true,
    hasEvidence: true,
    hasScan: false,
    hasFurnishLayout: false,
    evidenceCount: 7,
    riskSummary: "临近主路且窗框有渗水痕迹，建议复看并确认维修责任。",
    thumbnail: "coast"
  },
  {
    id: "H04",
    title: "都市 Loft 小宅",
    latitude: 31.2324,
    longitude: 121.4589,
    address: "静安区昌平路 580 号",
    price: "¥4,350/月",
    deposit: "¥4,350",
    moveInCost: "约 ¥13,050",
    commuteMinutes: 15,
    distance: "0.8 km",
    riskCount: 1,
    highRiskCount: 0,
    score: 88,
    status: "favorite",
    statusLabel: "已收藏 · 待看房",
    isFavorite: true,
    hasVisited: false,
    hasEvidence: false,
    hasScan: false,
    hasFurnishLayout: false,
    evidenceCount: 0,
    riskSummary: "层高适合做软装规划，收纳空间需要现场复核。",
    thumbnail: "loft"
  },
  {
    id: "SCAN-01",
    modelId: "H05",
    title: "现场扫描房型",
    latitude: 31.2218,
    longitude: 121.4707,
    address: "黄浦区北京东路附近",
    price: "待补充",
    deposit: "待补充",
    moveInCost: "待计算",
    commuteMinutes: 22,
    distance: "2.0 km",
    riskCount: 2,
    highRiskCount: 0,
    score: 83,
    status: "scanned",
    statusLabel: "刚刚扫描 · 待完善",
    isFavorite: false,
    hasVisited: true,
    hasEvidence: true,
    hasScan: true,
    hasFurnishLayout: false,
    evidenceCount: 3,
    riskSummary: "已保存尺寸节点，建议补充水电表、门窗与噪音记录。",
    thumbnail: "scan"
  }
];

globalThis.RoomarkPropertyData = {
  all() {
    return globalThis.ROOMARK_PROPERTIES;
  },
  findById(id) {
    return globalThis.ROOMARK_PROPERTIES.find((property) => property.id === id || property.modelId === id);
  },
  findByTitle(title) {
    return globalThis.ROOMARK_PROPERTIES.find((property) => property.title === title);
  }
};
